using System;
using System.IO;

namespace AsmInstructionSetGenerator
{
    public class Program
    {
        private const string ToolLink = "// This file has been generated by zx-spectrum-tools from https://dgzornoza.github.io/zx-spectrum-tools/";

        public static void Main(string[] args)
        {
            Directory.CreateDirectory("output");

            string json = new JsonGenerator().ExtractInstructionSet();
            File.WriteAllText("output/z80asm-keywords.json", $"{ToolLink}{Environment.NewLine}{json}");
        }
    }
}
